<a href="https://colab.research.google.com/github/greeshmapj/AI-course-notes/blob/main/Sec26_Hyperparameter_Tuning_in_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📘 HYPERPARAMETER TUNING IN DEEP LEARNING

---

## 1️⃣ What are Hyperparameters?

Hyperparameters are values set **before training starts**.  
They are **NOT learned from data**.

---

### 🔹 Two Types of Hyperparameters

| Type | Examples |
|------|----------|
| Model Hyperparameters | Number of layers, Number of neurons, Activation functions |
| Training Hyperparameters | Learning rate, Batch size, Epochs |

---

# 2️⃣ Important Hyperparameters in Deep Learning

---

## 🔥 1. Learning Rate (η)

The **most important hyperparameter** in deep learning.

- Too High → Divergence (loss increases)
- Too Low → Very slow convergence
- Good value → Smooth and stable convergence

### Example:

`optimizer = Adam(learning_rate=0.001)`

### 📌 Typical Range:

- 0.1  
- 0.01  
- 0.001 (very common)  
- 0.0001  

---

## 🔥 2. Batch Size

Number of samples processed before updating weights.

| Small Batch | Large Batch |
|-------------|------------|
| Noisy updates | Stable updates |
| Better generalization | Faster computation |
| Slower training per epoch | Requires more memory |

### Common Values:

- 16  
- 32  
- 64  
- 128  

---

## 🔥 3. Number of Epochs

Number of times the model sees the full dataset.

- Too High → Overfitting  
- Too Low → Underfitting  

### Use Early Stopping:

`EarlyStopping(monitor='val_loss', patience=5)`

---

## 🔥 4. Number of Hidden Layers & Neurons

Controls model complexity.

### Example:

`Dense(128, activation='relu')`  
`Dense(64, activation='relu')`

- More neurons → More learning capacity  
- Too many neurons → Overfitting  
- Too few neurons → Underfitting  

---

## 🔥 5. Activation Function

Adds non-linearity to the model.

Common activation functions:

- ReLU  
- LeakyReLU  
- Tanh  
- Sigmoid  
- Softmax (for multi-class classification)  

---

## 🔥 6. Optimizer

Determines how weights are updated.

| Optimizer | Best For |
|-----------|----------|
| SGD | Simple problems |
| Adam | Most commonly used |
| RMSProp | RNN / sequential data |
| Adagrad | Sparse data |

---

## 🔥 7. Dropout Rate

Used to prevent overfitting.

### Example:

`Dropout(0.3)`

### Common Values:

- 0.2  
- 0.3  
- 0.5  

---

## 🔥 8. Regularization

Prevents overfitting by penalizing large weights.

- L1 Regularization  
- L2 Regularization  

### Example:

`kernel_regularizer=tf.keras.regularizers.l2(0.01)`

---

# 🧠 Hyperparameter Tuning Methods

---

## 1️⃣ Manual Search

- Try combinations manually  
- Simple to implement  
- Time-consuming  

---

## 2️⃣ Grid Search

Tries **all possible combinations**.

Example:

- Learning rate: [0.01, 0.001]  
- Batch size: [32, 64]  

Total Models = 2 × 2 = 4  

⚠ Computationally expensive for large search spaces.

---

## 3️⃣ Random Search

- Randomly selects combinations  
- More efficient than Grid Search  
- Works well for large parameter spaces  

---

## 4️⃣ Bayesian Optimization (Advanced)

- Uses probability to select the next best parameters  
- Smarter and more efficient than Grid Search  

### Popular Libraries:

- Keras Tuner  
- Optuna  

---

In [ ]:
# 🌸 ANN on Iris Dataset

# 1️⃣ Import Libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# 2️⃣ Load Dataset
iris = load_iris()
X = iris.data
y = iris.target

# 3️⃣ One-Hot Encode Target
y = to_categorical(y, 3)

# 4️⃣ Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 5️⃣ Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 6️⃣ Build ANN Model
model = Sequential([
    Dense(16, activation='relu', input_shape=(4,)),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax') #multiclass classificatoin
])

# 7️⃣ Compile Model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# 8️⃣ Train Model
history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

# 9️⃣ Evaluate Model
loss, accuracy = model.evaluate(X_test, y_test)
print("\nTest Accuracy:", accuracy)

# 🔟 Predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

print("\nConfusion Matrix:\n", confusion_matrix(y_true, y_pred_classes))
print("\nClassification Report:\n", classification_report(y_true, y_pred_classes))

Epoch 1/100

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.4015 - loss: 1.2071 - val_accuracy: 0.6667 - val_loss: 1.0947
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4003 - loss: 1.1929 - val_accuracy: 0.6667 - val_loss: 1.0615
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3704 - loss: 1.1575 - val_accuracy: 0.6667 - val_loss: 1.0307
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4094 - loss: 1.1109 - val_accuracy: 0.6250 - val_loss: 1.0010
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4635 - loss: 1.0618 - val_accuracy: 0.6667 - val_loss: 0.9725
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3723 - loss: 1.0466 - val_accuracy: 0.6667 - val_loss: 0.9468
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4327 - loss: 1.0035 - val_accuracy: 0.6667 - val_loss: 0.9207
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4091 - loss: 0.9925 - val_accuracy: 0.6667 - val_loss: 0.8968
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5049 - loss: 0.9743 - val_accuracy: 0.7500 - val_loss: 0.8733
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6979 - loss: 0.9401 - val_accuracy: 0.7500 - val_loss: 0.8496
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7278 - loss: 0.8941 - val_accuracy: 0.7500 - val_loss: 0.8261
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7650 - loss: 0.9131 - val_accuracy: 0.7917 - val_loss: 0.8040
Epoch 13/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7359 - loss: 0.8821 - val_accuracy: 0.7917 - val_loss: 0.7824
Epoch 14/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7528 - loss: 0.8557 - val_accuracy: 0.8333 - val_loss: 0.7594
Epoch 15/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7518 - loss: 0.8536 - val_accuracy: 0.8333 - val_loss: 0.7385
Epoch 16/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7039 - loss: 0.8630 - val_accuracy: 0.8750 - val_loss: 0.7181
Epoch 17/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7406 - loss: 0.8129 - val_accuracy: 0.8750 - val_loss: 0.6971
Epoch 18/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7778 - loss: 0.7840 - val_accuracy: 0.8750 - val_loss: 0.6768
Epoch 19/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7235 - loss: 0.7951 - val_accuracy: 0.8750 - val_loss: 0.6564
Epoch 20/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7652 - loss: 0.7882 - val_accuracy: 0.9167 - val_loss: 0.6369
Epoch 21/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8616 - loss: 0.7004 - val_accuracy: 0.9167 - val_loss: 0.6165
Epoch 22/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8524 - loss: 0.6885 - val_accuracy: 0.9167 - val_loss: 0.5952
Epoch 23/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7796 - loss: 0.6741 - val_accuracy: 0.9167 - val_loss: 0.5774
Epoch 24/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8253 - loss: 0.6310 - val_accuracy: 0.9167 - val_loss: 0.5588
Epoch 25/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7847 - loss: 0.6556 - val_accuracy: 0.9167 - val_loss: 0.5432
Epoch 26/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8335 - loss: 0.5770 - val_accuracy: 0.9167 - val_loss: 0.5263
Epoch 27/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8143 - loss: 0.5889 - val_accuracy: 0.9167 - val_loss: 0.5094
Epoch 28/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8835 - loss: 0.5118 - val_accuracy: 0.9167 - val_loss: 0.4906
Epoch 29/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8299 - loss: 0.5436 - val_accuracy: 0.9167 - val_loss: 0.4754
Epoch 30/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8760 - loss: 0.5047 - val_accuracy: 0.9167 - val_loss: 0.4586
Epoch 31/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8760 - loss: 0.4843 - val_accuracy: 0.9167 - val_loss: 0.4443
Epoch 32/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8824 - loss: 0.4677 - val_accuracy: 0.9167 - val_loss: 0.4314
Epoch 33/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8643 - loss: 0.4475 - val_accuracy: 0.9167 - val_loss: 0.4183
Epoch 34/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8943 - loss: 0.4358 - val_accuracy: 0.9167 - val_loss: 0.4066
Epoch 35/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8924 - loss: 0.4186 - val_accuracy: 0.9167 - val_loss: 0.3943
Epoch 36/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8330 - loss: 0.4544 - val_accuracy: 0.9167 - val_loss: 0.3856
Epoch 37/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8949 - loss: 0.3731 - val_accuracy: 0.9167 - val_loss: 0.3752
Epoch 38/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8649 - loss: 0.3790 - val_accuracy: 0.9167 - val_loss: 0.3666
Epoch 39/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9036 - loss: 0.3570 - val_accuracy: 0.9167 - val_loss: 0.3575
Epoch 40/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8716 - loss: 0.3495 - val_accuracy: 0.9167 - val_loss: 0.3490
Epoch 41/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8683 - loss: 0.3709 - val_accuracy: 0.9167 - val_loss: 0.3418
Epoch 42/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8979 - loss: 0.3223 - val_accuracy: 0.9167 - val_loss: 0.3345
Epoch 43/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9222 - loss: 0.3552 - val_accuracy: 0.9167 - val_loss: 0.3295
Epoch 44/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9393 - loss: 0.2918 - val_accuracy: 0.9167 - val_loss: 0.3225
Epoch 45/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.9235 - loss: 0.2990 - val_accuracy: 0.9167 - val_loss: 0.3187
Epoch 46/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9219 - loss: 0.2855 - val_accuracy: 0.9167 - val_loss: 0.3121
Epoch 47/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9320 - loss: 0.2798 - val_accuracy: 0.9583 - val_loss: 0.3075
Epoch 48/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8990 - loss: 0.3164 - val_accuracy: 0.9583 - val_loss: 0.3014
Epoch 49/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9363 - loss: 0.2798 - val_accuracy: 0.9583 - val_loss: 0.2951
Epoch 50/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.8967 - loss: 0.3131 - val_accuracy: 0.9583 - val_loss: 0.2914
Epoch 51/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9074 - loss: 0.2924 - val_accuracy: 0.9583 - val_loss: 0.2862
Epoch 52/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9286 - loss: 0.2728 - val_accuracy: 0.9583 - val_loss: 0.2836
Epoch 53/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9524 - loss: 0.2966 - val_accuracy: 0.9583 - val_loss: 0.2789
Epoch 54/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9359 - loss: 0.2859 - val_accuracy: 0.9583 - val_loss: 0.2740
Epoch 55/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9690 - loss: 0.2236 - val_accuracy: 0.9583 - val_loss: 0.2676
Epoch 56/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9783 - loss: 0.2115 - val_accuracy: 0.9583 - val_loss: 0.2643
Epoch 57/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9656 - loss: 0.2378 - val_accuracy: 0.9583 - val_loss: 0.2600
Epoch 58/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9661 - loss: 0.2372 - val_accuracy: 0.9583 - val_loss: 0.2576
Epoch 59/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9333 - loss: 0.2287 - val_accuracy: 0.9583 - val_loss: 0.2557
Epoch 60/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9423 - loss: 0.2435 - val_accuracy: 0.9583 - val_loss: 0.2511
Epoch 61/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9661 - loss: 0.2222 - val_accuracy: 0.9583 - val_loss: 0.2493
Epoch 62/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9341 - loss: 0.2551 - val_accuracy: 0.9583 - val_loss: 0.2445
Epoch 63/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9359 - loss: 0.2300 - val_accuracy: 0.9583 - val_loss: 0.2429
Epoch 64/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9616 - loss: 0.2008 - val_accuracy: 0.9583 - val_loss: 0.2369
Epoch 65/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9567 - loss: 0.2048 - val_accuracy: 0.9583 - val_loss: 0.2320
Epoch 66/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9341 - loss: 0.2030 - val_accuracy: 0.9583 - val_loss: 0.2280
Epoch 67/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9378 - loss: 0.2067 - val_accuracy: 0.9583 - val_loss: 0.2245
Epoch 68/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9497 - loss: 0.1949 - val_accuracy: 0.9583 - val_loss: 0.2227
Epoch 69/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9504 - loss: 0.1977 - val_accuracy: 0.9583 - val_loss: 0.2218
Epoch 70/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9793 - loss: 0.1703 - val_accuracy: 0.9583 - val_loss: 0.2204
Epoch 71/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9783 - loss: 0.1730 - val_accuracy: 0.9583 - val_loss: 0.2171
Epoch 72/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9557 - loss: 0.1813 - val_accuracy: 0.9583 - val_loss: 0.2142
Epoch 73/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9545 - loss: 0.1809 - val_accuracy: 0.9583 - val_loss: 0.2111
Epoch 74/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9661 - loss: 0.1443 - val_accuracy: 0.9583 - val_loss: 0.2059
Epoch 75/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9619 - loss: 0.1702 - val_accuracy: 0.9583 - val_loss: 0.2021
Epoch 76/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9519 - loss: 0.1859 - val_accuracy: 0.9583 - val_loss: 0.2031
Epoch 77/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9668 - loss: 0.1540 - val_accuracy: 0.9583 - val_loss: 0.2023
Epoch 78/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9497 - loss: 0.1629 - val_accuracy: 0.9583 - val_loss: 0.1998
Epoch 79/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9467 - loss: 0.1623 - val_accuracy: 0.9583 - val_loss: 0.1966
Epoch 80/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9753 - loss: 0.1262 - val_accuracy: 0.9583 - val_loss: 0.1945
Epoch 81/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9656 - loss: 0.1340 - val_accuracy: 0.9583 - val_loss: 0.1914
Epoch 82/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9567 - loss: 0.1437 - val_accuracy: 0.9583 - val_loss: 0.1876
Epoch 83/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9563 - loss: 0.1404 - val_accuracy: 0.9583 - val_loss: 0.1884
Epoch 84/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9626 - loss: 0.1201 - val_accuracy: 0.9583 - val_loss: 0.1864
Epoch 85/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9393 - loss: 0.1720 - val_accuracy: 0.9583 - val_loss: 0.1856
Epoch 86/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9619 - loss: 0.1476 - val_accuracy: 0.9583 - val_loss: 0.1815
Epoch 87/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9589 - loss: 0.1392 - val_accuracy: 0.9583 - val_loss: 0.1793
Epoch 88/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9475 - loss: 0.1303 - val_accuracy: 0.9583 - val_loss: 0.1799
Epoch 89/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9753 - loss: 0.1197 - val_accuracy: 0.9583 - val_loss: 0.1803
Epoch 90/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9783 - loss: 0.1078 - val_accuracy: 0.9583 - val_loss: 0.1764
Epoch 91/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9423 - loss: 0.1460 - val_accuracy: 0.9583 - val_loss: 0.1757
Epoch 92/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9609 - loss: 0.1183 - val_accuracy: 0.9583 - val_loss: 0.1756
Epoch 93/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9522 - loss: 0.1190 - val_accuracy: 0.9583 - val_loss: 0.1712
Epoch 94/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9155 - loss: 0.1643 - val_accuracy: 0.9583 - val_loss: 0.1709
Epoch 95/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9318 - loss: 0.1315 - val_accuracy: 0.9583 - val_loss: 0.1710
Epoch 96/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9753 - loss: 0.1032 - val_accuracy: 0.9583 - val_loss: 0.1682
Epoch 97/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9656 - loss: 0.1121 - val_accuracy: 0.9583 - val_loss: 0.1635
Epoch 98/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9571 - loss: 0.0957 - val_accuracy: 0.9583 - val_loss: 0.1615
Epoch 99/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9586 - loss: 0.1176 - val_accuracy: 0.9583 - val_loss: 0.1636
Epoch 100/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9753 - loss: 0.1071 - val_accuracy: 0.9583 - val_loss: 0.1645
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0882

Test Accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [ ]:
!pip install keras-tuner #not inbuilt ( so we have to install)

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.78.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.18.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.1.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 881.3 kB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
# 🌸 Hyperparameter Tuning on Iris using Keras Tuner

# 1️⃣ Install (run once if not installed)
# !pip install keras-tuner

# 2️⃣ Import Libraries
import numpy as np
import tensorflow as tf
import keras_tuner as kt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout #to drop neurons
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

# 3️⃣ Load Dataset
iris = load_iris()
X = iris.data
y = iris.target #3 class,  setosa, virginica, versicolor

# 4️⃣ One-Hot Encoding
y = to_categorical(y, 3) #labelbinarizer

# 5️⃣ Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 6️⃣ Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



"""model = Sequential([
    Dense(16, activation='relu', input_shape=(4,)), #hiddenlayer1
    Dense(8, activation='relu'), #hiddenla
    Dense(3, activation='softmax') #multiclass classificatoin
])"""



# 7️⃣ Build Model Function for Tuner
def build_model(hp):
    model = Sequential()

    # Tune number of neurons
    model.add(Dense(
        units=hp.Int('units_1', min_value=8, max_value=64, step=8), #8,16,24,32,40,48,56,64
        activation='relu',
        input_shape=(4,)
    )) #hidden layer1

    # Tune second hidden layer neurons
    model.add(Dense(
        units=hp.Int('units_2', min_value=8, max_value=64, step=8),
        activation='relu'
    ))

    # Tune dropout
    model.add(Dropout(
        rate=hp.Choice('dropout_rate', values=[0.2, 0.3, 0.4])
    ))
    """If dropout = 0.3
→ 30% of neurons(bubble) are randomly deactivated per batch.

Why? Because neural networks tend to:Memorize training data Depend heavily on specific neurons Dropout forces the network to: Learn robust patterns Avoid co-dependency"""

    model.add(Dense(3, activation='softmax'))



    # Tune learning rate
    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=hp.Choice('learning_rate', values=[0.01, 0.001, 0.0001])
        ),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model


    """👉 How big a step the model takes while updating weight
If learning rate is:

Too High (0.1) → Training unstable, may overshoot

Too Low (0.0001) → Training very slow

Balanced (0.001) → Smooth convergence

🎯 What it affects:

Speed of training

Stability

Final accuracy

It does NOT prevent overfitting directly."""

# 8️⃣ Initialize Tuner=1
tuner = kt.RandomSearch(
    build_model, # we built it earlier
    objective='val_accuracy',
    max_trials=10, #10 random combinations
    directory='iris_tuning',
    project_name='iris_ann'
)

# 9️⃣ Search Best Hyperparameters
tuner.search(
    X_train, y_train,
    epochs=50,
    validation_split=0.2,
    batch_size=16,
    verbose=1
)

# 🔟 Get Best Model
best_model = tuner.get_best_models(num_models=1)[0]

# 1️⃣1️⃣ Evaluate on Test Set
loss, accuracy = best_model.evaluate(X_test, y_test)
print("\nBest Model Test Accuracy:", accuracy)

# 1️⃣2️⃣ Show Best Hyperparameters
best_hp = tuner.get_best_hyperparameters(1)[0]
print("\nBest Hyperparameters:")
print("Units Layer 1:", best_hp.get('units_1'))
print("Units Layer 2:", best_hp.get('units_2'))
print("Dropout Rate:", best_hp.get('dropout_rate'))
print("Learning Rate:", best_hp.get('learning_rate'))

# 1️⃣3️⃣ Classification Report
y_pred = np.argmax(best_model.predict(X_test), axis=1)
y_true = np.argmax(y_test, axis=1)

print("\nClassification Report:\n")
print(classification_report(y_true, y_pred))

Reloading Tuner from iris_tuning/iris_ann/tuner0.json

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 566ms/step - accuracy: 0.9667 - loss: 0.1183

Best Model Test Accuracy: 0.9666666388511658

Best Hyperparameters:
Units Layer 1: 64
Units Layer 2: 16
Dropout Rate: 0.3
Learning Rate: 0.01
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

In [ ]:
#tuner2: plan b
tuner = kt.BayesianOptimization(
    build_model,
    objective='val_accuracy',
    max_trials=10,
    directory='iris_tuning',
    project_name='iris_ann'
)

# diabetics data

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/diabetes_patient_data.csv")
data

,Age,BMI,Glucose,BloodPressure,Gender,Smoking,ExerciseLevel,Diabetes
0,58,38.54,172.22,123.70,Female,Yes,Low,1
1,48,18.17,144.70,120.32,Female,No,High,0
2,34,22.96,143.65,62.88,Female,No,High,0
3,62,26.04,120.84,91.58,Male,Yes,Medium,0
4,27,28.73,135.15,134.46,Male,Yes,High,0
...,...,...,...,...,...,...,...,...
995,45,36.16,163.55,78.14,Male,Yes,Low,1
996,53,24.15,118.25,113.60,Male,Yes,High,0
997,64,38.73,183.07,97.47,Female,Yes,Medium,0
998,25,37.21,164.96,121.88,Male,Yes,Low,1
999,56,21.56,154.20,69.87,Male,Yes,High,0

data: https://docs.google.com/spreadsheets/d/1uenHEX2d16etzjtf1XjFTSh0RbMNcQdWd5ng8yC-QT0/edit?usp=sharing

In [ ]:
numeric_cols = ["Age", "BMI", "Glucose", "BloodPressure"]
categorical_cols = ["Gender", "Smoking", "ExerciseLevel"]

# One-hot encode categorical
data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

# Separate X and y
X = data.drop("Diabetes", axis=1)
y = data["Diabetes"]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale ONLY numeric columns
scaler = StandardScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [ ]:
X_test

,Age,BMI,Glucose,BloodPressure,Gender_Male,Smoking_Yes,ExerciseLevel_Low,ExerciseLevel_Medium
521,-0.132124,0.852166,-0.304633,-0.283075,True,False,False,False
737,-1.241098,-0.881462,-1.691647,0.654064,True,False,True,False
740,0.006498,0.339314,0.343580,1.351698,True,False,False,False
660,0.838228,0.375497,0.615085,-0.343952,True,True,True,False
411,0.699607,1.394908,0.563281,-0.971822,False,True,True,False
...,...,...,...,...,...,...,...,...
408,-0.132124,0.720020,0.889513,0.530090,False,True,False,False
332,-0.270746,-0.667512,1.471575,1.267271,True,False,False,False
208,0.907539,-0.813816,1.618486,1.353920,True,False,True,False
613,-1.310409,-1.251156,-0.081477,1.248608,True,True,False,True
78,1.531337,0.403814,-1.103740,-1.130012,False,False,False,False

In [ ]:
model = Sequential()

model.add(Dense(16, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 289 (1.13 KB)

 Trainable params: 289 (1.13 KB)

 Non-trainable params: 0 (0.00 B)

Parameters = (input_features × neurons) + bias, (8 × 16) + 16 = 128 + 16 = 144 ✅,(16 × 8) + 8 = 128 + 8 = 136 ✅,(8 × 1) + 1 = 8 + 1 = 9 ✅

In [ ]:
history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.2106 - loss: 0.8109 - val_accuracy: 0.3500 - val_loss: 0.7340
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4346 - loss: 0.7159 - val_accuracy: 0.7063 - val_loss: 0.6504
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7163 - loss: 0.6348 - val_accuracy: 0.7875 - val_loss: 0.5887
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8069 - loss: 0.5738 - val_accuracy: 0.8313 - val_loss: 0.5368
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8282 - loss: 0.5247 - val_accuracy: 0.8375 - val_loss: 0.4952
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8072 - loss: 0.5081 - val_accuracy: 0.8375 - val_loss: 0.4622
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8124 - loss: 0.4707 - val_accuracy: 0.8375 - val_loss: 0.4349
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7952 - loss: 0.4585 - val_accuracy: 0.8375 - val_loss: 0.4089
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7966 - loss: 0.4367 - val_accuracy: 0.8375 - val_loss: 0.3839
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8199 - loss: 0.3954 - val_accuracy: 0.8438 - val_loss: 0.3594
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8285 - loss: 0.3559 - val_accuracy: 0.8562 - val_loss: 0.3343
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8210 - loss: 0.3391 - val_accuracy: 0.8625 - val_loss: 0.3092
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8527 - loss: 0.3047 - val_accuracy: 0.8813 - val_loss: 0.2838
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8706 - loss: 0.2730 - val_accuracy: 0.9125 - val_loss: 0.2590
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9162 - loss: 0.2624 - val_accuracy: 0.9438 - val_loss: 0.2353
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9410 - loss: 0.2323 - val_accuracy: 0.9688 - val_loss: 0.2144
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9622 - loss: 0.2023 - val_accuracy: 0.9750 - val_loss: 0.1943
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9815 - loss: 0.1907 - val_accuracy: 0.9812 - val_loss: 0.1764
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9799 - loss: 0.1780 - val_accuracy: 0.9875 - val_loss: 0.1602
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9906 - loss: 0.1485 - val_accuracy: 0.9937 - val_loss: 0.1460
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9958 - loss: 0.1406 - val_accuracy: 0.9937 - val_loss: 0.1329
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9908 - loss: 0.1197 - val_accuracy: 0.9937 - val_loss: 0.1213
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9956 - loss: 0.1109 - val_accuracy: 0.9937 - val_loss: 0.1111
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9977 - loss: 0.1049 - val_accuracy: 0.9937 - val_loss: 0.1016
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9943 - loss: 0.0958 - val_accuracy: 0.9937 - val_loss: 0.0930
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0845 - val_accuracy: 0.9937 - val_loss: 0.0853
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9906 - loss: 0.0831 - val_accuracy: 1.0000 - val_loss: 0.0779
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9956 - loss: 0.0704 - val_accuracy: 1.0000 - val_loss: 0.0716
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9950 - loss: 0.0664 - val_accuracy: 1.0000 - val_loss: 0.0658
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9936 - loss: 0.0634 - val_accuracy: 1.0000 - val_loss: 0.0604

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

y_pred = (model.predict(X_test) > 0.5).astype("int32")
print(classification_report(y_test, y_pred))

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9973 - loss: 0.0659

WARNING:tensorflow:5 out of the last 10 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x781b698a6480> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

Test Accuracy: 0.9950000047683716
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       169
           1       0.97      1.00      0.98        31

    accuracy                           0.99       200
   macro avg       0.98      1.00      0.99       200
weighted avg       1.00      0.99      1.00       200