<a href="https://colab.research.google.com/github/greeshmapj/AI-course-notes/blob/main/Sec32_Mini_NLP_Project_Sentiment_Analysis_of_Movie_Reviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🌍 1. What is NLP?

Imagine you talk to **Alexa**, **Google Assistant**, or **ChatGPT** — and it replies in human language.  
That happens because of **NLP — Natural Language Processing**.

👉 **Definition:**  
NLP is a part of **Artificial Intelligence (AI)** that helps computers **understand, interpret, and respond** to human language.

It helps machines deal with **text or speech**, just like humans do.

---

# 🗣️ 2. Why NLP is Needed?

Humans talk using **natural languages** (English, Malayalam, Hindi, etc.).  
Computers understand **numbers (0s and 1s)**.

So, NLP acts as a bridge between:

🧍 **Human Language** ↔ 💻 **Machine Understanding**

**Example:**  
You say: “Show me good restaurants nearby.”  
➡️ NLP breaks it into meaning → finds your intent → gives a list of restaurants.

---

# 📱 3. Real-Life Applications of NLP

| Application | What it does | Example |
|--------------|---------------|----------|
| 🗨️ Chatbots | Understand and reply to messages | ChatGPT |
| 🗣️ Voice Assistants | Understand speech and give answers | Alexa, Siri, Google Assistant |
| 📩 Spam Detection ✅ | Filters unwanted emails | Gmail spam filter |
| 🌐 Translation | Converts one language to another | Google Translate |
| 📰 Text Summarization ✅ | Shortens long articles | News summary apps |
| 💬 Sentiment Analysis  ✅| Finds emotion behind text | "This movie was great!" → Positive |
| 🧾 Document Search | Helps find info faster | Search bar in PDFs or apps |

---

# 🧩 4. How NLP Works (Simple Steps)

You can think of it like making **tea ☕** —  
each step has to be done properly for the final output to make sense.

| Step | Process | Example |
|------|----------|----------|
| 1️⃣ | Text Input | "I love learning Python!" |
| 2️⃣ | Text Cleaning / Preprocessing | remove punctuation, convert to lowercase (case sensitive)|
| 3️⃣ | Tokenization | Split into words → [“i”, “love”, “learning”, “python”] |
| 4️⃣ | Stopword Removal | Remove words like “i”, “the”, “is” |
| 5️⃣ | Stemming / Lemmatization | “learning” → “learn” |
| 6️⃣ | Feature Extraction | Convert words to numbers (Bag of Words, TF-IDF, embeddings) |
| 7️⃣ | Model / Algorithm | Apply ML model → predict meaning/sentiment |
| 8️⃣ | Output | “Positive” sentiment |

---

# 🧮 5. Simple Example

**Input:**  
“This movie was wonderful!”

**Output:**  
Sentiment → **Positive 😊**

**How it happens:**  
NLP reads text → converts it into numbers → ML model learns → predicts the emotion.

In [ ]:
"apple" == "apple" #case sensitive

True

# 🧠 6. Important NLP Concepts (Simplified)

| Term | Meaning | Example |
|------|----------|----------|
| **Tokenization** | Splitting text into small parts (words/sentences) | “I love AI” → [“I”, “love”, “AI”] |
| **Stopwords** | Common words removed for clarity | “is”, “the”, “a” |
| **Stemming** | Cutting a word to its root form | “running” → “run” |
| **Lemmatization** | Similar to stemming but grammatically correct | “better” → “good” |
| **NER (Named Entity Recognition)** | Finds names, places, and dates | “Swathi works at ict → PERSON: Swathi, ORG: ict |
| **POS Tagging (Part of Speech)** | Identifies parts of speech | “Python is amazing” → Python(NN), is(VB), amazing(JJ) |

---

# ⚙️ 7. Tools & Libraries

| Library | Use |
|----------|-----|
| **NLTK** | Easy for learning basics |
| **spaCy** | Fast and used in production |
| **TextBlob** | Great for beginners |
| **Hugging Face Transformers** | For deep learning-based models (BERT, GPT) |

---

# 🚀 8. Where NLP is Used in Real Life

- **Instagram / Twitter:** Detects hate speech or inappropriate content  
- **Customer Reviews:** Finds whether feedback is positive or negative  
- **Healthcare:** Analyzes doctor notes  
- **Education:** Chatbots to assist learners  
- **Search Engines:** Understands meaning behind queries  

---

# 💬 9. Small Project Idea (For Practice)

**Mini Project:** Sentiment Analysis on Movie Reviews 🎬

**Input:** A few sample reviews  
**Task:** Predict if each review is *Positive* or *Negative*  
**Libraries:** `pandas`, `sklearn`, `TfidfVectorizer`, `LogisticRegression`  

✨ *This can be your students’ first hands-on NLP project!*

---

# 🌟 10. Summary

- NLP helps **machines understand human language**.  
- It is used in **chatbots, translators, voice assistants**, and more.  
- The process involves **cleaning text → converting it to numbers → applying ML**.  
- It’s one of the **most powerful and growing fields in AI today.**

# 🧠  **Important NLP Concepts**
---

## 1️⃣ Tokenization
**Meaning:** Splitting text into smaller units (words, sentences, or subwords).  
**Why Important:** Most NLP models work on tokens, not raw sentences.

**Example:**  
Text: `"I love AI"`

**Code (using NLTK):**

In [ ]:
import nltk #library # natural language tool kit
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize, sent_tokenize

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
text = "I love AI. sIt' amazing!"
# Sentence tokenization
sentences = sent_tokenize(text)
print("Sentences:", sentences)
# Word tokenization
words = word_tokenize(text)
print("Words:", words)
#diff between sent_tokenize,word_tokenize

Sentences: ['I love AI.', "sIt' amazing!"]
Words: ['I', 'love', 'AI', '.', 'sIt', "'", 'amazing', '!']

# **2️⃣ Stopwords**

Meaning: Common words (like "is", "the", "a") that are often removed to reduce noise.
Why Important: They don’t carry much meaning in many NLP tasks.

Code (using NLTK):

In [ ]:
{1,1,1,"a","a","a"} # no duplicants

{1, 'a'}

In [ ]:
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
stop_words

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [ ]:
text = "This is a simple sentence."
words = word_tokenize(text)
words #list

['This', 'is', 'a', 'simple', 'sentence', '.']

In [ ]:
for i in words:
  print(i.lower())

this
is
a
simple
sentence
.

In [ ]:
filtered_words = [i for i in words if i.lower() not in stop_words]
print("Filtered Words:", filtered_words) # non stopping words

Filtered Words: ['simple', 'sentence', '.']

In [ ]:
filtered_words

['simple', 'sentence', '.']

# avoid punctuation and make it lower case

In [ ]:
# Sample long sentence
text = "Hello there! I am learning Natural Language Processing, and it's really amazing to see how machines understand text."

# Stopwords and punctuation
stop_words = set(stopwords.words('english'))

In [ ]:
import string
punctuation = set(string.punctuation)
punctuation

{'!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~'}

In [ ]:
# Sample long sentence
text = "Hello there! I am learning Natural Language Processing 55, and it's really amazing to see how machines understand text."

# Stopwords and punctuation
stop_words = set(stopwords.words('english'))

In [ ]:
# Tokenize
words = word_tokenize(text)

words

['Hello',
 'there',
 '!',
 'I',
 'am',
 'learning',
 'Natural',
 'Language',
 'Processing',
 '55',
 ',',
 'and',
 'it',
 "'s",
 'really',
 'amazing',
 'to',
 'see',
 'how',
 'machines',
 'understand',
 'text',
 '.']

In [ ]:
# Remove stopwords and punctuation, keep only alphabetic words
filtered_words = [i.lower() for i in words if i.lower() not in stop_words and i not in punctuation]

print("Filtered Words:", filtered_words)

Filtered Words: ['hello', 'learning', 'natural', 'language', 'processing', '55', "'s", 'really', 'amazing', 'see', 'machines', 'understand', 'text']

In [ ]:
text="""The sunset was still beautiful.
The sky still turned yellow.

But something was missing.

That’s when she realized—it was never just about the sunset."""

words = word_tokenize(text)
filtered_words = [i.lower() for i in words if i.lower() not in stop_words and i not in punctuation]
filtered_words

['sunset',
 'still',
 'beautiful',
 'sky',
 'still',
 'turned',
 'yellow',
 'something',
 'missing',
 '’',
 'realized—it',
 'never',
 'sunset']

# plan B to remove punctuations

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

# Sample long sentence
text = "Hello there! I am learning Natural Language Processing 55, and it's really amazing to see how machines understand text."

# Stopwords and punctuation
stop_words = set(stopwords.words('english'))

# Tokenize
words = word_tokenize(text) #["hello","happy"]

# Remove stopwords, punctuation, and non-alphabetic tokens
filtered_words = [w.lower() for w in words if w.lower() not in stop_words and w.isalpha()]#alphabet(remove punctuations&digits)

print("Filtered Words:", filtered_words)

Filtered Words: ['hello', 'learning', 'natural', 'language', 'processing', 'really', 'amazing', 'see', 'machines', 'understand', 'text']

# plan c

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

text = "Patient's BP is 120 and heart rate is 80."

# Stopwords
stop_words = set(stopwords.words('english'))

# Tokenize
words = word_tokenize(text)

# Keep words and numbers, remove punctuation
filtered_words = [w.lower() for w in words if w.lower() not in stop_words and w.isalnum()]

print(filtered_words)

['patient', 'bp', '120', 'heart', 'rate', '80']

# punctuations - removal
1.  punctuations list [".","/"] not in
2. isalpha
3.isalnum

In [ ]:
text="""India is my country. %% All Indians are my brothers and sisters.
I love my country and I am proud of its rich and varied heritage.
I shall always strive to be worthy of it.
I shall give my parents, teachers and all elders respect and treat && everyone with courtesy$$$&
To my country and my * people, I pledge my devotion. In their well-being and prosperity alone, lies my happiness"""

In [ ]:
text

'India is my country. %% All Indians are my brothers and sisters.\nI love my country and I am proud of its rich and varied heritage.\nI shall always strive to be worthy of it.\nI shall give my parents, teachers and all elders respect and treat && everyone with courtesy$$$&\nTo my country and my * people, I pledge my devotion. In their well-being and prosperity alone, lies my happiness'

In [ ]:
# Stopwords
stop_words = set(stopwords.words('english'))

# Tokenize
words = word_tokenize(text)

# Keep words and numbers, remove punctuation
filtered_words = [w.lower() for w in words if w.lower() not in stop_words and w.isalnum()]

print(filtered_words)

['india', 'country', 'indians', 'brothers', 'sisters', 'love', 'country', 'proud', 'rich', 'varied', 'heritage', 'shall', 'always', 'strive', 'worthy', 'shall', 'give', 'parents', 'teachers', 'elders', 'respect', 'treat', 'everyone', 'courtesy', 'country', 'people', 'pledge', 'devotion', 'prosperity', 'alone', 'lies', 'happiness']

# **3️⃣ Stemming**

Meaning: Reducing words to their root form (may not be grammatically correct).
Why Important: Helps reduce vocabulary size and generalize similar words.

Code (using NLTK PorterStemmer):

In [ ]:

from nltk.stem import PorterStemmer

stemmer = PorterStemmer()
words = ["running", "runs", "ran", "easily", "fairly"]
stemmed_words = [stemmer.stem(i) for i in words]
print("Stemmed Words:", stemmed_words)

Stemmed Words: ['run', 'run', 'ran', 'easili', 'fairli']

# **4️⃣ Lemmatization**

Meaning: Reduces words to their base or dictionary form (grammatically correct).
Why Important: Produces proper root forms which are more meaningful than stemming.

Code (using NLTK WordNetLemmatizer):

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet #stopwords
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()
words = ["singing", "runs", "easily", "fairly"]
lemmatized = [lemmatizer.lemmatize(w, pos="v") for w in words]
print(lemmatized)

['sing', 'run', 'easily', 'fairly']

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Because lemmatize() assumes noun (pos='n') by default.

So:

“runs” → noun form is “run” ✅

“running” → noun form stays “running” ❌ (since it’s not seen as a verb)

✅ Correct way (with POS tagging)

To get the true root form, you should specify the POS tag manually or automatically:

In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [ ]:
print(lemmatizer.lemmatize("running", pos="v"))  # v = verb
print(lemmatizer.lemmatize("better", pos="a"))   # a = adjective
print(lemmatizer.lemmatize("easily", pos="r")) #adverb

run
good
easily

## 🌿 Stemming vs 🍃 Lemmatization

| Feature              | **Stemming**                                                                  | **Lemmatization**                                                                  |
| -------------------- | ----------------------------------------------------------------------------- | ---------------------------------------------------------------------------------- |
| **Definition**       | A process that chops off word endings to get the root form (called a *stem*). | A process that reduces a word to its base or dictionary form (called a *lemma*).   |
| **Method**           | Applies simple **rule-based heuristics** (e.g., remove “ing”, “ed”).          | Uses **vocabulary and morphological analysis** (understands word meaning and POS). |
| **Example**          | *"running" → "run"*<br>*"studies" → "studi"*                                  | *"running" → "run"*<br>*"studies" → "study"*                                       |
| **Output words**     | May not be valid English words (e.g., *“comput”* from *“computing”*).         | Always valid dictionary words.                                                     |
| **Accuracy**         | Faster but less accurate.                                                     | Slower but more accurate.                                                          |
| **Library examples** | `PorterStemmer`, `SnowballStemmer` (in NLTK).                                 | `WordNetLemmatizer` (in NLTK), `spacy` lemmatizer.                                 |
| **Use case**         | When **speed** matters more than accuracy (like quick search).                | When **meaning** and **context** matter (like NLP tasks, translation, etc.).       |

---

### 🧠 In short:
- **Stemming** → Mechanical cutting → “quick and dirty.”  
- **Lemmatization** → Linguistically smart → “slow but meaningful.”

# **5️⃣ NER (Named Entity Recognition)**

Meaning: Identifies names of people, organizations, locations, dates, etc.
Why Important: Helps extract meaningful information from text automatically.

Code (using spaCy):

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = " Trivandrum is gods own country"
doc = nlp(text)

for i in doc.ents:
    print(i.text, i.label_) #Geo-Political Entity — refers to countries, cities, or states.

Trivandrum GPE

# project 1

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split #ml
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
data = {
    'review': [
        "I loved this movie,987 it was fantastic!",
        "Absolutely terrible, waste of time.",
        "It was okay, not too bad but not great either.",
        "The performance was brilliant and emotional.",
        "Worst movie ever made.",
        "A masterpiece of storytelling and visuals!",
        "Not good, I didn’t like the plot.",
        "Excellent film! Great direction and acting.",
        "It was boring and too long.",
        "Loved it! Highly recommended.","The movie was  bad, I  dont enjoyed it."
    ],
    'sentiment': ['Positive', 'Negative', 'Neutral', 'Positive', 'Negative',
                  'Positive', 'Negative', 'Positive', 'Negative', 'Positive',"Negative"]
}

df = pd.DataFrame(data)
df

                                            review sentiment
0            I loved this movie, it was fantastic!  Positive
1              Absolutely terrible, waste of time.  Negative
2   It was okay, not too bad but not great either.   Neutral
3     The performance was brilliant and emotional.  Positive
4                           Worst movie ever made.  Negative
5       A masterpiece of storytelling and visuals!  Positive
6                Not good, I didn’t like the plot.  Negative
7      Excellent film! Great direction and acting.  Positive
8                      It was boring and too long.  Negative
9                    Loved it! Highly recommended.  Positive
10         The movie was  bad, I  dont enjoyed it.  Negative

In [ ]:
import pandas as pd
import nltk
import re #replace
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download stopwords and lemmatizer resources (only first time)
nltk.download('stopwords')
nltk.download('wordnet')

# Initialize tools
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer() #lemma, dict

# Function to clean text
def preprocess_text(text):
    text = text.lower()                            # 1. Lowercase
    text = re.sub(r'[^a-z\s]', '', text)           # 2. Remove punctuation/numbers (plan d)
    words = text.split()                           # 3. Tokenize
    words = [w for w in words if w not in stop_words]  # 4. Remove stopwords
    words = [lemmatizer.lemmatize(w,pos="v") for w in words]   # 5. Lemmatization
    return ' '.join(words)

# Apply preprocessing
df['clean_review'] = df['review'].apply(preprocess_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
df

,review,sentiment,clean_review
0,"I loved this movie, it was fantastic!",Positive,love movie fantastic
1,"Absolutely terrible, waste of time.",Negative,absolutely terrible waste time
2,"It was okay, not too bad but not great either.",Neutral,okay bad great either
3,The performance was brilliant and emotional.,Positive,performance brilliant emotional
4,Worst movie ever made.,Negative,worst movie ever make
5,A masterpiece of storytelling and visuals!,Positive,masterpiece storytelling visuals
6,"Not good, I didn’t like the plot.",Negative,good didnt like plot
7,Excellent film! Great direction and acting.,Positive,excellent film great direction act
8,It was boring and too long.,Negative,bore long
9,Loved it! Highly recommended.,Positive,love highly recommend
10,"The movie was bad, I dont enjoyed it.",Negative,movie bad dont enjoy

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['clean_review'])
y = df['sentiment']

In [ ]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 39 stored elements and shape (11, 34)>

In [ ]:
import pandas as pd
# not nessasary
# Convert sparse matrix to a DataFrame
X_df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

# Display the first few rows
X_df.head()

,absolutely,acting,bad,boring,brilliant,didnt,direction,dont,either,emotional,...,okay,performance,plot,recommended,storytelling,terrible,time,visuals,waste,worst
0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.00000,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,0.5,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.00000,...,0.000000,0.00000,0.0,0.0,0.0,0.5,0.5,0.0,0.5,0.000000
2,0.0,0.0,0.459441,0.0,0.00000,0.0,0.0,0.0,0.537507,0.00000,...,0.537507,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
3,0.0,0.0,0.000000,0.0,0.57735,0.0,0.0,0.0,0.000000,0.57735,...,0.000000,0.57735,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.00000,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.529621

In [ ]:
X_df.style.background_gradient(cmap='hot')

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Accuracy: 0.25

Classification Report:
               precision    recall  f1-score   support

    Negative       0.25      1.00      0.40         1
    Positive       0.00      0.00      0.00         3

    accuracy                           0.25         4
   macro avg       0.12      0.50      0.20         4
weighted avg       0.06      0.25      0.10         4

In [ ]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.25

Classification Report:
               precision    recall  f1-score   support

    Negative       0.25      1.00      0.40         1
    Positive       0.00      0.00      0.00         3

    accuracy                           0.25         4
   macro avg       0.12      0.50      0.20         4
weighted avg       0.06      0.25      0.10         4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
sample = ["The movie was  bad, I  dont enjoyed it."] # step1: vectorizer 2. model apply
sample_vector = vectorizer.transform(sample)
print(model.predict(sample_vector))

['Negative']